version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to the React app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to the Spring Boot app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budget_planner
      SPRING_DATASOURCE_USERNAME: budget_user
      SPRING_DATASOURCE_PASSWORD: password123

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: budget_planner
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
