version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budget_planner
      SPRING_DATASOURCE_USERNAME: budget_user
      SPRING_DATASOURCE_PASSWORD: password123

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: budget_planner
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

